create extension if not exists pgcrypto;

create table if not exists app_users (id uuid primary key default gen_random_uuid(), name text not null, email text unique not null, role text not null check (role in ('owner','consultant')), user_id uuid, created_at timestamptz default now());
create table if not exists clients (id uuid primary key default gen_random_uuid(), company_name text not null, contact_name text not null, contact_email text, contact_phone text, user_id uuid, created_at timestamptz default now());
create table if not exists travellers (id uuid primary key default gen_random_uuid(), client_id uuid not null references clients on delete cascade, full_name text not null, passport_number text, passport_number_confidence numeric, passport_number_source text, dob date, dob_confidence numeric, dob_source text, expiry_date date, expiry_date_confidence numeric, expiry_date_source text, nationality text, nationality_confidence numeric, nationality_source text, mrz_data text, mrz_confidence numeric, mrz_source text, verification_status text not null default 'unreviewed' check (verification_status in ('unreviewed','client_confirmed','verified','rejected')), review_status text not null default 'unreviewed', user_id uuid, created_at timestamptz default now());
create table if not exists cases (id uuid primary key default gen_random_uuid(), case_number text unique not null, client_id uuid not null references clients, assigned_to uuid references app_users, origin text not null, destination text not null, departure_date date not null, return_date date, trip_type text not null check (trip_type in ('oneway','roundtrip','multicity')), passenger_count int not null check (passenger_count > 0), cabin_class text not null, notes text, status text not null default 'new' check (status in ('new','in_progress','quoted','confirmed','booked','ticketed','closed')), intake_source text not null default 'manual' check (intake_source in ('web','email','whatsapp','manual')), escalation_flag boolean default false, escalation_reason text, next_action text, next_action_deadline timestamptz, user_id uuid, created_at timestamptz default now());
create table if not exists quotations (id uuid primary key default gen_random_uuid(), case_id uuid not null references cases on delete cascade, itinerary_text text, parsed_segments jsonb default '[]', parsed_segments_confidence numeric, parsed_segments_source text, parsed_segments_review_status text default 'unreviewed', base_fare numeric not null default 0, taxes numeric not null default 0, service_fee numeric not null default 0, total_amount numeric generated always as (base_fare + taxes + service_fee) stored, baggage_info text, fare_conditions text, expiry_date timestamptz, status text not null default 'draft' check (status in ('draft','approved','sent','accepted','rejected')), approved_by uuid references app_users, user_id uuid, created_at timestamptz default now());
create table if not exists bookings (id uuid primary key default gen_random_uuid(), case_id uuid not null references cases on delete cascade, quotation_id uuid references quotations, pnr text unique not null, pnr_source text not null check (pnr_source in ('gds','airline','supplier')), itinerary jsonb default '[]', quoted_amount numeric not null, ttl timestamptz not null, ttl_source text not null, status text not null default 'unticketed' check (status in ('unticketed','ticketed','cancelled','expired')), user_id uuid, created_at timestamptz default now());
create table if not exists payments (id uuid primary key default gen_random_uuid(), booking_id uuid not null references bookings on delete cascade, amount numeric not null, evidence_file_path text not null, status text not null default 'pending_verification' check (status in ('pending_verification','verified','rejected')), verified_by uuid references app_users, verification_note text, user_id uuid, created_at timestamptz default now());
create table if not exists tickets (id uuid primary key default gen_random_uuid(), booking_id uuid not null references bookings on delete cascade, payment_id uuid references payments, ticket_number text unique not null, issue_date date not null, final_amount numeric not null, e_ticket_path text, status text not null default 'issued' check (status in ('issued','voided','exchanged')), issued_by uuid references app_users, user_id uuid, created_at timestamptz default now());
create table if not exists service_cases (id uuid primary key default gen_random_uuid(), booking_id uuid references bookings, ticket_id uuid references tickets, case_id uuid references cases, type text not null check (type in ('reissuance','refund','cancellation','void','waiver')), request_details text not null, status text not null default 'requested' check (status in ('requested','in_review','accepted','completed','rejected')), result_summary text, user_id uuid, created_at timestamptz default now());
create table if not exists documents (id uuid primary key default gen_random_uuid(), entity_type text not null, entity_id uuid not null, file_path text not null, file_type text not null, user_id uuid, created_at timestamptz default now());
create table if not exists reminders (id uuid primary key default gen_random_uuid(), entity_type text not null, entity_id uuid not null, reminder_type text not null check (reminder_type in ('ttl','payment','missing_docs','client_response')), due_at timestamptz not null, status text not null default 'scheduled' check (status in ('scheduled','sent','dismissed')), message text not null, user_id uuid, created_at timestamptz default now());
create table if not exists audit_logs (id uuid primary key default gen_random_uuid(), actor_id uuid references app_users, action text not null, entity_type text not null, entity_id uuid not null, details jsonb default '{}', user_id uuid, created_at timestamptz default now());

do $$ declare t text; begin foreach t in array array['app_users','clients','travellers','cases','quotations','bookings','payments','tickets','service_cases','documents','reminders','audit_logs'] loop execute format('alter table %I enable row level security', t); execute format('drop policy if exists demo_all on %I', t); execute format('create policy demo_all on %I for all using (true) with check (true)', t); end loop; end $$;

insert into app_users (id,name,email,role) values ('00000000-0000-0000-0000-000000000001','A N M Younus','owner@travelpro.dhaka','owner') on conflict do nothing;
insert into clients (id,company_name,contact_name,contact_email,contact_phone) values ('10000000-0000-0000-0000-000000000001','Sky Trade BD','Farhana Rahman','travel@skytrade.bd','+8801711000001'), ('10000000-0000-0000-0000-000000000002','Dhaka Garments Group','Mahmud Hasan','admin@dgg.bd','+8801711000002'), ('10000000-0000-0000-0000-000000000003','Global Relief Bangladesh','Nusrat Jahan','ops@globalrelief.bd','+8801711000003') on conflict do nothing;
insert into cases (case_number,client_id,assigned_to,origin,destination,departure_date,return_date,trip_type,passenger_count,cabin_class,status,intake_source,next_action,next_action_deadline) values ('TP-260917-001','10000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000001','DAC','DXB','2026-10-15','2026-10-20','roundtrip',2,'Economy','new','whatsapp','Prepare fare options',now()+interval '1 day'), ('TP-260917-002','10000000-0000-0000-0000-000000000002','00000000-0000-0000-0000-000000000001','DAC','CAN','2026-10-22','2026-10-29','roundtrip',4,'Economy','in_progress','email','Collect passport copies',now()+interval '8 hours'), ('TP-260917-003','10000000-0000-0000-0000-000000000003','00000000-0000-0000-0000-000000000001','DAC','KUL','2026-11-02',null,'oneway',1,'Business','quoted','manual','Client follow-up',now()+interval '2 days') on conflict (case_number) do nothing;
create or replace function prevent_audit_change() returns trigger language plpgsql as $$ begin raise exception 'audit logs are append-only'; end $$;
drop trigger if exists audit_logs_immutable on audit_logs; create trigger audit_logs_immutable before update or delete on audit_logs for each row execute function prevent_audit_change();
